volumes:
  pihole-data:
  tailscale-data:

services:
  pihole: # https://github.com/pi-hole/docker-pi-hole/
    image: pihole/pihole:${PIHOLE_VERSION:-latest}
    restart: unless-stopped
    network_mode: service:tailscale
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ:-America/New_York}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      VIRTUAL_HOST: pihole
      WEBTHEME: default-dark
      DNSMASQ_LISTENING: all
      DNSSEC: 'false'
      SKIPGRAVITYONBOOT: 'true'
    volumes:
      - pihole-data:/etc/pihole

  tailscale: # https://tailscale.com/kb/1282/docker
    image: tailscale/tailscale:${TAILSCALE_VERSION:-latest}
    restart: unless-stopped
    hostname: pihole
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: 'false'
      TS_HOSTNAME: pihole
    volumes:
      - tailscale-data:/var/lib/tailscale